---
title: "Visionary Final"
author: "Justin DePue"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## library packages

```{r warning=FALSE, message=FALSE}

library(tseries)
library(lubridate)
library(here)
library(tidyverse)
library(outliers)
library(ggplot2)
library(forecast)

```

## load the data

```{r warning=FALSE}

# automatically set the working directory as personal local path to R project
# so the file path in read.csv can work for everyone
setwd(here())

# load the data
electricity_prices.df <- read.csv("./Data/Average_retail_price_of_electricity.csv", header = TRUE, skip=4)

nc_electricity.df<-electricity_prices.df[228,4:(ncol(electricity_prices.df))]%>%pivot_longer(cols=everything(), names_to = 'my_date', values_to = 'price_per_kWh')

# examine whether there is missing value or not
summary(nc_electricity.df)
# there is no missing value

nc_electricity.df$price_per_kWh<-as.numeric(nc_electricity.df$price_per_kWh)

ts_electricity<-ts(rev(nc_electricity.df[,2]), start=c(2001,1), frequency=12)

plot(ts_electricity, col="red", ylab="$/kWh", xlab="Date", main="NC Residential Electricity Cost")
  

# Import Natural Gas data

natural_gas.df <- read.csv("./Data/NC_NaturalGas.csv", header = TRUE, skip=2,col.names = c("year", "price"))

#Check for missing data. There is an extra row with an NA at the end of the data, so I removed it with na.omit

summary(na.omit(natural_gas.df))

#create timeseries for natural gas

ts_NG<-ts(na.omit(natural_gas.df[,2]), start=c(1989,1), frequency=12)

# plot raw timeseries
plot(ts_NG, col="blue", ylab="$/Mcf", xlab="Date", main="NC Residential Natural Gas Cost")



```


```{r, warning=FALSE}
# convert natural gas data from $/Mcf to $/kWh based on 80% heating efficiency

natural_gas.df$kwh_equiv<-(natural_gas.df$price/2.431318)

natural_gas.df<-na.omit(natural_gas.df)

ts_gas_equiv<-ts(natural_gas.df[,3], start=c(1989,1), frequency=12)

ts_gas_equiv<-window(ts_gas_equiv, start=c(2001, 1))

autoplot(ts_gas_equiv)




ts.plot(ts_gas_equiv, ts_electricity, gpars = list(col = c("red", "blue")), xlab="Date", ylab="cents/kWh", main="Comparison of Natural Gas and Electricity Costs")
legend("topleft", bty="n", lty=c(1,1), col=c("red","blue"),
       legend=c(" Natural Gas ", " Electricity "))

#Create Dataframe with both Gas & Electricity prices...
#create new date column
new_date<-seq(as.Date("2001/1/1"), by = "month", length.out = nrow(ts_electricity))

#bind date, gas, & electricity
nc_energy.df<-cbind.data.frame("Month_Date"=new_date,"electricity"=nc_electricity.df$price_per_kWh,"gas_equiv"=ts_gas_equiv)

#Subtract Gas price from Electricity price
nc_energy.df$cost_diff<-(nc_energy.df$electricity - nc_energy.df$gas_equiv)

```

```{r}
#Decompose TS

decomp_elec<-decompose(ts_electricity, type="additive")
decomp_gas<-decompose(ts_NG, type="multiplicative")

#remove seasonality
ts_elec_ns<-(ts_electricity-decomp_elec$seasonal)
ts_gas_ns<-(ts_NG-decomp_gas$seasonal)


```

```{r}
par(mfrow=c(1,2))
Acf(ts_electricity, lag.max=40, main="ACF Electricity")
Acf(ts_elec_ns, lag.max=40, main="ACF Non-Seasonal Electricity")

par(mfrow=c(1,2))
Pacf(ts_electricity, lag.max=40, main="PACF Electricity")
Pacf(ts_elec_ns, lag.max=40, main="PACF Non-Seasonal Electricity")



par(mfrow=c(1,2))
Acf(ts_NG, lag.max=40, main="ACF Natural Gas")
Acf(ts_gas_ns, lag.max=40, main="ACF Non-Seasonal Gas")

par(mfrow=c(1,2))
Pacf(ts_NG, lag.max=40, main="PACF Natural Gas")
Pacf(ts_gas_ns, lag.max=40, main="PACF Non-Seasonal Gas")
```


```{r}
#forecast Electricity SARIMA

arima.e.model<-auto.arima(window(ts_electricity, end=c(2022,1)))
arima.e.forecast<-forecast(arima.e.model, h=12)

autoplot(ts_electricity)+
autolayer(arima.e.forecast$mean)


#Gas SARIMA forecast
arima.gas.model<-auto.arima(window(ts_gas_equiv, end=c(2022,1)))
arima.gas.forecast<-forecast(arima.gas.model, h=12)

autoplot(ts_gas_equiv)+
autolayer(arima.gas.forecast$mean)
```

